[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03f932fdd9aafcb8139720ef15c0d0bcb6e495ec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "10e887e7a7bf033c30fd949d6f9ce2cae60aad81656ff2f30cce03e80825d819"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07ebcc6b5e7782809445f440fc1383e241966c12"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "a081967ee6f78296c2174cc96f1aaefe95b6ab38fe81811e92e4b086eea7a3a0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4aae7e4134b95b4dc94f295e329b77ef9ef66b29"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "c256279d3bb81acd349c4ca10eb83f07bb97dbf9276df2fffa26db454392e43d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d5b0f52463b7442895b59b5be7242bafcfcb3f5"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "0c1420b7db9a415cc7763fcae1363f36559905d137614efa194d6290cddfcf91"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba7928ce632c144a50d70a3be8b79f0978b0c976"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "daafafd24e3232799a4c520ed1ec22b00a33f2ca4ab92d9abdfcd867956970d5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25be1f8728ca8556a9cf73fdb1db19c8e9362840"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "8642e090c8f0f71845ea79c82caad03edef5ffcc24f363d731cb6fc84b818a4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "323788d74faab9a12f86ded7a212d30fc4085ad0"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "c6b217bc1ebf0942ce7971f0f80e1f11df86af6da15cd36ee901d482a8a68c9a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eda4ced49f4d061957efa3223defa65f9a52c3d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "e44e8acc7b29f22f679901809134a0ca01cde07e57ceed6b62e7343fb52b8989"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "850a797502f5a25287b2b731ee89d4fdc2218699"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ca10562a52ee2dc0a5a86cbeaa69e28c79242083f6a33399d6e543bfaab55596"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2077d7e8e43576c9b845d5c9bdd0bed5530b8577"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "59718be58d1ced93c3efdba0709291e0df86c22f9a8b1b3c121c8abd1e867b56"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57da60d2ace3810b7bde46c3168c9e5f74d20afd"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ffd2bcfd1145e30d540fb7a3990c771bdcf8697f9ec72ac890db401346cbfeb6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "db88fc144379d5e74ffec1aada385c314a450c95"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "6167f579e1ab222393fdf27fc24b3e7a522d5ff177af76987699c509897dc372"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.501+0/GAP_pkg_ferret.v100.0.501.x86_64-unknown-freebsd.tar.gz"
