[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "10c022c6ce7570ecc146ee94a7dfef396324f446"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "050363e39667f2896105dfc58c9697391c056f4c6f6d6df390ca2fe6487252e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b54124dd7e0b6cd23036b061db358195627025a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "860ca0ead4fb375b6308f8bba30b5c620441a59e5f6533338022f4fad58e3bb3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8e07b7f66a504d3d82607623e5b73be88e3f554"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ac7ff5a69005ac5eceb05d9aee76833623f4bab906b219ba0cd3a2ff45471d72"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a105308c0a60d21fc93a07a12196285a0f5e93ae"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "2c0200d49805ab90f407a751eeb8c5cbea2125893596ed0e8fdec9391872fd06"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b22cdd50781d6553c0b5641969db6f22a4d9c412"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "bd11d6ad8100286d4687f987d2063888868eaae40c1fd0fec68428cdc9dc9f6d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39fb1f792dbcfd38ccf1c7b3ea0e1143fc86cbed"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "cb6ffc3ae5454e65659fc6e7d2be1a60e515f4da9f69811dffb15da202100d76"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4996731db380616de1dec7143a87278e807ed90"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "243103c1a6a195f4a623d26d64fbe025d971476f2144f466143b0a7f90c2230b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "7fd137f267fce77bb18e12daa30cf12b5d9e2b5e"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "b4da40e81d38f67fa0fbfa1eed05ec2237974ddff5db90b37f72549841088766"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1719eba97a22ca42adfb410a7e8dc6b29f1bccd9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "6164a274bfa7095bfe41dcd7325f177e3711af7ee5a00f11bd081367a3ebd28c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5872aaa8e3f3a3164e1d37bde10b811b047ce8c0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "394041f33ce13108a24ee36583035fa2972c5abadacd8093d9e193a797bda66d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf940db5ae3a909ab0cf7dd38238ae7abb73225f"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "1f1d6924aa93c60b4265fd3d92ebe7b71e364d08ebefb09f15ddbafbb24a2be3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8459a87bb1a9679a42aed763cf91c7b7fd02e938"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "858a3e29f1735c24b4de8e4b7c415d5a9bddc2d9fdf408fedbd0caff14e20f7c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "71ace56012797170ae93a5d7566aebaf42ec2d26"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "35fecebcf1468aa0a16f7ebbfd6198518a8dc747c633a72373a4fdbe389e17d0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.901+0/GAP_pkg_ferret.v100.0.901.x86_64-unknown-freebsd.tar.gz"
