[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "8f5002e3a500f33b23b4daede9ae667dbda628c8"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "f3598ce625981173225d88e4088fe727220ee5138a7f21aeeb7ed2fb07f9e184"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a14b22394ef7e19da6960543567ff65f65f8648"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "dbef314af54cd200ed5feba2eb6db10d02c8f4632c56b90992016423ce4f3a4d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ff24934d9b1dbbf30c71fb75fb6fec846ede6c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "0d48b766b9ca0afb1823e351f126a9d2476087d289130a20f8d86d10666cd28c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2710c9ec85d3cb79f10b43a58bcaf4aacf24dc8"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "6894885f8cc17c843cbb3879ed4d2caa1395f0d0cf4e3463bb4e2942df996475"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d760389ea77d603c8430af105b7fb5e3f9db995"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "b6fb2d51ae4569546d9253ddf11b33dfc2adb65ecf1b0fc59f8f9ad1df10f136"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9f94a2dd2afcaafa92f707162ea73aa87abbe70"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "7fd58c06560dde12d863b7818d0db732b06887c8e88c179f666f0181640d0b83"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8ec44cf13e70dca49f8532f0e284cde4f9a1f21"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "2166f1a051134945a357d0ad342158b85d7f5a24cb1fb5bbc32f8782243ac605"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "0e684af41e7a744875d94b113eaa453310dbb9fb"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "ae141366d673f56a32b47798fed790170b53ca7e5859199953d03ece42caff81"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c7c095d8c0921628fd62031591881cecde5e900"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "6426c183cd968273e7a682b911a6c5361c30518d7093cb826058d5b1acd47490"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b130b9480d16b38d6a885327480d8800dbdc18a6"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "7050c0752832af53e35ff4dc62f87f68654ccc1518e735084b4edaf80aaecaa9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1a66996d3601eaaa294d6de53da139ee0322fe6"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "02d99cd9cdf915bbc6e697143edcccdf805c07bc17188f88b28adb0ddffdedc2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e37058d272175470f50bc13cba951a4e8c56c14"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "20c4a7d834579a40d7f0d031d7a1baaf9f535d916b812c23540b9dd615016591"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "d216e5e1a8893a4a40f28474a33f077fa3fa3cf5"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "f3a9b3e0132b8376f2d31688e881ca004136ebed4d80b4e4513c3d1ae603817d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.800+1/GAP_pkg_ferret.v100.0.800.x86_64-unknown-freebsd.tar.gz"
