[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "54dd693118e00428ca1da650e5b0cfe3af46fe6c"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "0b120067fd7ee299f96d305965134f65bf678c95f32c0285a4aa7ac9f4138b17"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9becf94c533f9076c2c2365e50a6e1389bce6a0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "3bd16cf125d04a92d7e74a933c6b7f2efeb813cce837438c6c519c737c18ba2e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d9f16162a1655abce371e488e23dc69a98f03d0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "20b71a798032195b1c40170d7124e4e2a16410293851c502170c38c251998e73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cd7b055df4611b3446a0eaf3af0a316f917c663"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "e8c724a6bd44544ee71727354bfe48f3cade77965a0f3318352b94bd1d947866"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58456c8903280b007820f62a82fc0af29ae8f7f6"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "f53181dadc3eff4ea7d7780e3b63ac0ffec4885c2c6b600163de82a6354759e8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdf1d276bb0fb83fadbc0d08fff8a662d7a75791"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "1b71f2418b093a6517be3f81df3da6688f6c8f3ad0a54a9fd12779e606c1fa78"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e1c80ba8b1ceffad759c515aa1cfc9fc4b2ae92"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ee5c09ad48373c9ea21d4fe0f7bff8c432851fa6185e9c2214e7ac3a4c7f9fee"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "ed1448eccf9d45420d7ca9f0afffa383132cf101"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "652bfb1066d9731d017c0064515a249c392a2696804600c71c96f4d21ea9205c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cbbe04634534470d9381008f02ad13eb3f27501"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "c587c2f1bc394510be22bd50255fbcfaf04a916ae89ae483f9998dbcd6d06484"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44fe31b1874e422f3fa2ea29c11401d3c101069f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "f24a736c9447a587319db80b07b079b28ecbb304e67c73a27a7e41e1031638b0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a32363a540f86d1b2a7c6cd6c63146f138da505c"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "c258833ba3deadad054e85697c7bf85b7ceeda2ed6463bb27d5ccbd4bbb2b2b9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69ce57a521c705b4a62dcaeb1084724fe3b9d461"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "683d8ae478e6ffc08b390689f606453862573024086395018dbf582734bcbac1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "9fe6334f7f7201e42e66cc329a2411df120414f5"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "b4af7693eebdb93211648dc468f40dc4f0eeb5fef5d4033209e5bbb841e58494"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1400+0/GAP_pkg_ferret.v100.0.1400.x86_64-unknown-freebsd.tar.gz"
