[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "cc3e3b1928418d653229a2c02533e30a154f1809"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "61da09563ab0e9418b8c86213ae01dd6b4c26d309d23ed6760aeb80e43586219"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e15608b4a9f2787903d4a9400796190edcad38e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "f8cb0c3839a90e88266e7c280135edf6da907f2ad94c989c9fa3936956f6beeb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04f7d92a1297408cb3d78b0c1250dd77b0c9a8e4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "9303a0350d0e38024ed9f4ba50cc85019a507fc9175185d2b7fbd969dac84a2b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98ddc1e20e954eb78503956abff1524c524ea163"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "5b7794d22399e976cd795b2cb8f99a9dfef8d8c07b8961c30ed5f68e3ba4d8d4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd77a877afa95a87c492e02a6cb4e58ac0d75f86"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "b5dc9ec702ab13a272db229f9847e42da041bac060afbec480bed0fce04fb597"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "46928bd63e17df0d4ab923687635e4523bab5417"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "01a39d5573420d2dca1a49e265a365aa29b4d71b320b0765b8942d3e0314f43a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4eaa5b109f3de1f26d6742fcd8a8cd91e6b8c96c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "43d06bad5ac194c8ad8b3895e96fa623f635d022fc3fc939d44111b4aabde428"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a13b9094b91049d6b720664ee3015b5fdd23c1cb"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ff6f80a9b10707f9e57e79f7b2e6836824317d143b29f600dcb7790ff3bb08a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7020e66c7432f0075507f490eb96410c27233733"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "5e4017112f4f19924de624881b313b24b387ce46b5b51ce7b57293d4e78534dd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.riscv64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c711e67b9d06fe8591b46195681db89d29bbd41"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "7714567c96bacce5ad0377bf7bb60b0ad41880fac5387deea9d30189d0bf5219"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "6447f7a6a3aef2fb133db7d6f1b8b6a38636880c"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "bcf715adb42269b7703d74ae9392c77ffdfacf22f1c908f518136fc44a69c51b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5712174af7cc37978f69639873886ab102e7720"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "9324fedb9f348cf8830d4c9df9ccd72b1dfbce5b140f02d9a14ae04641d85a33"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a50f700fcde3994d2f0e1ecd0f799d5d2e932950"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "3f7b3cf8afbbb235aed874055bb8f44f6e026b1f0debcb0ad8ee18dcecbb3e6b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7040b9cab9d454d93bfc7d33bf89a60ddb6bfc6"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "1c6d22e9e6304c444da670df7016729f5bd503867b534e5e3905a01e02e9a361"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e20441ccc9bf11a6c0a9363b562c1984ae53dd74"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "214336a45694c5c09951679b8951a165fb50f72934819f528e6d9ec4c71b50ad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "99286ac72d2ef7d94e29e8f71be563fa7e868e49"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "05dbb1173525c5231173566bfe8be20458effd3cd0c986da364aff4cfac2989c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.1402+0/GAP_pkg_ferret.v100.0.1402.x86_64-unknown-freebsd.tar.gz"
