[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "79b5cf9866e818793139ab789dfbce4c333fa556"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "17eae43d4c7cc64026a917d97e13560d2ee8a2e7fa5fbbeb865125ad00fbdcc0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8263751a6ea3e583db23b1c476186688c6116cb9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "277a25880a911692d068adf0e5761f741de0c3c54e2e5a5eda9d693b967d983b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.aarch64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f275520d864f0f29e338f2186244d01e296a9e9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "04cc6070bab8d5d8f9a8ed1fec0157cf03a859e5684cc7b7aaa81c8002262f62"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dbad6558aeac757a330e1decafefb70bfedcac2"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "c1c6229d92620e3003ba99d9b7474c730a47eb5272bf961b0fda446b9dc4d1e0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.aarch64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b66236e72522678d7445d878f2c7846b30ab7f9"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "52ff6d898ce09d6276621622da611442de074086b521b9eb8d47dbc62a705e7a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63bbec89e1ec557f37b682aaab1e729bc596371a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "e83e83ca98d716065742ac62fb62ca7771fec8ef0c7bb4e78bde117750da6584"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b98dfec3d3984b5c9ff1b07f668b0e6cbda4d10"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "ee7dc8d7c5ed4343159693183eca905c449f81915f9c53da31f664eaf77df589"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "26c4a2b506648d0cf19741da34fa1a550c7da469"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "f22b572669592632f732858ece2818f5c272a9068f6c04adc21f7fd0d7dbc099"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03941612eccd2186cc02ce77a57105a3e6c08e9a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "6cb6f8dd2ea529feb073bc8021748925fb244098610a34dc9258e3a466db4cad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-linux-gnu-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f19141049f16bfbcfc935640ab63bf800f804ad"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "0692acb2b29d02656b51b3b29805e4c8020e99eaebe3d1102d30fa9d776368a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeb63973fc03605d5a0fe71aa62dba677c361c01"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "b45dc77f6097e021709258d179080520d7bdaebf744c1714eb7323dd86c6ca4a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-linux-musl-cxx03.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b02a21c6d22f14b1422f265073d7354b70ed45"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "f914d5aeabe90d6fd0a763394364221a17e759c1b9cb799d3dc4a64976e9fc65"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "e13c9d4044f6d41aca39271eaa90ddf96c06cbf7"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "c992213b6eaf91826a8d277941d03b58805675147754229f3cc54ae7f6b2007e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v100.0.502+0/GAP_pkg_ferret.v100.0.502.x86_64-unknown-freebsd.tar.gz"
