[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "3681f9a44ea86eb51f81d89ab1d0372e1d9daf62"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "f427054d377da20c96093506519c28eeb058c2eeba6670d461c6074376fd989f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c01f5c238a19520673773ef78967fa9cceb8e379"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "50b3dbeb7022da0f431de40a1168374a7b01d957cd93b9862f3fc4460a1eec0e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2644220993eb8aa79dbb9dfbd1879cc19987ba1c"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "9fb3b4715bdea7bb383281259c251b7c0237fa2683c41fc3eafd3c3069d0320b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.aarch64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "aarch64"
git-tree-sha1 = "d00eefcbf0723a9796031843091acffceaea1f0c"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "e358496ff1869f395332b961638d9daf2a64b881f9aaefc80a71be9b96dd02c2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_ferret]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98c98612a97416c8ad5b84afe7ce2acd0b064c7a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "664a18a41becea4b9df25f67d8a29863733ba1ba9cfaf3fcbff85fbcfb0b0aec"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53267189fe890ca57003115be02310c6b53b8da0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "1dea7605af4a79874e313094252ae80f0ea9b48ac7a9834bb6804428896c3cfe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "3e33fcc4ef038e2d105d152a1d2eebf369e2e6ca"
os = "macos"

    [[GAP_pkg_ferret.download]]
    sha256 = "c65f81e04f5764863ec7be65b44aeb798282a799f01b0665725a7f8423853462"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43686b1293b2b866a381a0f58f9917c5fc6fd808"
libc = "glibc"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "19d1a713b8ef55fb75db3739950daeb186e0e38c8f4880fdb0a8334809c8b3cd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c1d7c5673299e7ec0820f7449837f7e4c8634c"
libc = "musl"
os = "linux"

    [[GAP_pkg_ferret.download]]
    sha256 = "c689ce86324f60fc756048e5345e76b0d3c45d9cda50dcd7f4bbd05d5aa6f3ad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.x86_64-linux-musl-cxx11.tar.gz"
[[GAP_pkg_ferret]]
arch = "x86_64"
git-tree-sha1 = "3306695d39955e586a9203288312d2310161a706"
os = "freebsd"

    [[GAP_pkg_ferret.download]]
    sha256 = "c7bf3bde53a5e7319fd4f2bd71409c1ec3ef12ecc30c9888580115ec6b30011c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_ferret_jll.jl/releases/download/GAP_pkg_ferret-v101.1600.0+0/GAP_pkg_ferret.v101.1600.0.x86_64-unknown-freebsd.tar.gz"
